name: setoko
description: Client app for Setoko.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.4+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_messaging: ^9.1.3
  firebase_analytics: ^8.0.3

  package_info: ^0.5.0-nullsafety
  shared_preferences: ^2.0.0-nullsafety
  intl: ^0.17.0-nullsafety.2

  mobx: ^2.0.0-nullsafety.2
  flutter_mobx: ^2.0.0-nullsafety.0
  provider: ^5.0.0
  flutter_local_notifications: ^5.0.0-nullsafety.0
  rxdart: ^0.26.0-nullsafety.0
  graphql_flutter: ^5.0.0-nullsafety.2
  json_annotation: ^4.0.1
  device_info: ^2.0.0
  dio: ^4.0.0
  webview_flutter: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.0


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/images/ic_template_brand.png
    - assets/svg/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path_ios: assets/icons/icon-1024.png
  image_path_android: assets/icons/icon-512-transparent.png
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: assets/icons/icon-512-transparent-extra-padding.png

flutter_intl:
  enabled: true
